version: '3.8'

services:
  # Mongdodb container.
  mongodb:
    image: mongo:latest
    restart: always
    # Persist dev database with database volume if needed
    # volumes:
    #   - database:/data/db
    # Basic health check with short interval.
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 3s
      retries: 10
    ports:
      - 27017:27017
    # Use the username and password defined in .env as mongodb root user definition.
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    # Mongo heavily clutters the logs, so all output is just routed to dev/null. Can be disabled for debugging purposes if necessary
    command: --logpath /dev/null

  # A simple mongdodb admin page container. Accessed at http://localhost:8081 with username: admin password: pass
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongodb:27017
    depends_on:
      - mongodb

  # authentication server
  auth-server:
    build: ./auth_server
    environment:
      PORT: 3001
      NODE_ENV: development
      DATABASE_URL: mongodb://root:secret@mongodb:27017
      JWR_SECRET: secret

  graphql:
    build: .
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: mongodb://root:secret@mongodb:27017
      AUTH_URL: http://auth-server:3001/api/v1
    depends_on:
      - auth-server
    ports:
      - 3000:3000
