name: backend-ci

on:
  push:
    paths:
      - backend/**
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/api:latest

      - name: Build and push auth server
        uses: docker/build-push-action@v5
        with:
          context: ./backend/auth_server
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/auth:latest
