name: API Tests

on:
  push:
    branches:
      - user_updates

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build auth server
        working-directory: ./backend/auth_server
        run: npm install && npm run build

      - name: Run auth server
        working-directory: ./backend/auth_server
        run: npm run start

      - name: Run tests
        working-directory: ./backend
        run: npm run test
